[issue #5] oauth로직에 헥사고날 적용
YAPP-Github/21st-Android-Team-1-BE pull request #6
Opened 2023-01-09 13:21 UTC by shinyubin989

## 개요
기존 Oauth 로직 리팩토링

## 작업 내용
기존에 만들어진 Oauth 로직을 헥사고날 아키텍쳐를 적용하여 리팩토링 하였습니다.

## issue
- resolved #5 

## 메모
추후 재리팩토링의 여지가 남아있습니다..ㅎ

close #

2023-01-10 15:10 UTC, Huey-J requested changes
패키지 구조에 대해 고민이 되는 것 말고는 깔끔한 것 같습니다.
제가 코멘트한 내용은 당연히 정답이 아니기 때문에 고민해 보시고 수정해 주시거나 답글 달아주세요!

2023-01-10 15:10 UTC, Huey-J commented on src/main/java/yapp/buddycon/web/member/auth/domain/OAuthMemberInfo.java
> +package yapp.buddycon.web.member.auth.domain;
OauthMemberInfo는 엔티티가 아니라는 점에서 member와는 다른 것 같습니다.
도메인 계층보다 어플리케이션 계층에 위치시키는건 어떨까요? meeron의 UserResponseDto 위치를 참고해서 코멘트 드립니다!

2023-01-10 15:10 UTC, Huey-J commented on src/main/java/yapp/buddycon/common/domain/AuthMember.java
> +package yapp.buddycon.common.domain;
약간 고민이 되는 내용입니다만, AuthMember도 OauthMemberInfo 코멘트 내용처럼 domain은 아니기 때문에 패키지가 바뀌는게 좋지 않을까 싶습니다.

2023-01-11 07:22 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/web/member/adapter/out/MemberCommandRepository.java
> +
기존에 패키지구조가 member안에 auth가 있는 구조였기 때문에 일단 그대로 구현을 했는데, 현희님과 동일한 의견입니다! 
user와 member의 의미가 모호해보여서, 후자로 진행할까 하는데 괜찮으실까요?

2023-01-11 07:42 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/web/member/auth/domain/OAuthMemberInfo.java
> +package yapp.buddycon.web.member.auth.domain;
흠흠그렇네요.. 패키지 이동이 필요해보입니다. 이게 request나 response로 나가는 dto는 아니라서 application.port.in 패키지 로 이동시킬까 합니다!

2023-01-11 07:59 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/common/domain/AuthMember.java
> +package yapp.buddycon.common.domain;
패키지 고민을 좀 해봤는데, 이부분은 common패키지가 아닌, auth.adapter.out에 놔도 괜찮을거같다는 생각입니다. 혹시 이부분은 어떻게 생각하실까요?

2023-01-11 09:21 UTC, Huey-J commented on src/main/java/yapp/buddycon/common/domain/AuthMember.java
> +package yapp.buddycon.common.domain;
흠.. 저는 말씀해주신 것 처럼 auth 도메인으로부터 생긴 클래스이기 때문에 auth 패키지 안에 넣는 것도 좋지만, 대부분의 도메인 영역에서 사용할 데이터 클래스라는 점에서 특정 도메인 안에 있는 것 보다는 common 처럼 공통 패키지에 있는게 좋을 것 같습니다.

근데 지금처럼 데이터만 있는 클래스가 아니라 auth와 관련된 비즈니스 로직이 추가적으로 들어간다면 common 보다는 auth 패키지 안이 더 적합해 보이기도 하네요..! 우선 유빈님이 더 적합해 보이는 곳에 놓아주시고 추후에 변경이 필요하면 그 때 또 논의해도 될 것 같습니다:)

2023-01-11 09:30 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/common/domain/AuthMember.java
> +package yapp.buddycon.common.domain;
common패키지에 넣는경우의 적합한 패키지 명이 아직 잘 떠오르지않아서, 우선 auth에 넣어놓고 추후에 좋은 네이밍이 떠오르면 그때 다시 한번 패키지 이동을 하는 것으로 하겠습니당
리뷰해주신것들 반영해서 머지하도록 할게요!

2023-01-11 09:36 UTC, Huey-J commented on src/main/java/yapp/buddycon/common/domain/AuthMember.java
> +package yapp.buddycon.common.domain;
네 알겠습니다~

2023-01-11 09:45 UTC, merged