[Issue #56] 쿠폰 상태 변경 로직 구현
YAPP-Github/21st-Android-Team-1-BE pull request #61
Opened 2023-02-09 09:55 UTC by shinyubin989

## 개요
쿠폰 상태 변경 로직 구현

## 작업 내용
- 현재 쿠폰의 상태가 USABLE이라면 USED로 변경할 수 있습니다.
- 현재 쿠폰의 상태가 USED라면 쿠폰의 만료기한이 '현재날짜'보다 큰 경우에만 USABLE상태로 변경할 수 있습니다.
  - 이 과정에서 @Transactional과 @Lock을 사용하였습니다.

## 메모

close #56

2023-02-09 13:55 UTC, Huey-J requested changes

2023-02-09 13:55 UTC, Huey-J commented on src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponQueryRepository.java
> +    return couponJpaRepository.findCouponUsed(memberId, couponId, date).orElseThrow(() -> new CustomException(ErrorCode.FAILED_TO_CHANGE_COUPON_STATE));
메소드와 Exception이 살짝 맞지 않는 것 같아요. 조회에 대한 예외를 반환하거나, 아니면 아예 밖에서 예외처리 하는 방식도 좋을 듯 합니다!

2023-02-09 13:55 UTC, Huey-J commented on src/main/java/yapp/buddycon/web/coupon/application/service/CouponService.java
> +    if (state.equals(CouponState.USABLE.name())) {
RequestDto에서 String이 아닌 CouponState를 받아오면 클라이언트나 개발자 입장에서 더 쉽게 이해가 가능할 것 같습니다.

2023-02-09 14:29 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponJpaRepository.java
> +  Optional<Coupon> findCouponUsed(Long memberId, Long couponId, LocalDate today);
동의합니다 !! 수정하겠습다!

2023-02-09 14:33 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/web/coupon/application/service/CouponService.java
> +    if (state.equals(CouponState.USABLE.name())) {
이것두 수정하겠습니당 ㅎㅎ

2023-02-09 14:34 UTC, shinyubin989 commented on src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponQueryRepository.java
> +    return couponJpaRepository.findCouponUsed(memberId, couponId, date).orElseThrow(() -> new CustomException(ErrorCode.FAILED_TO_CHANGE_COUPON_STATE));
메서드 명을 findCouponInUsedStateAndNotExpiredWithLock (USED상태이고 만료되지않은 것을 찾음)로 바꾸고,
Errorcode명을 INVALID_STATE_CHANGE_REQUEST로 바꾸는 건 어떨까요?!

2023-02-10 06:55 UTC, Huey-J approved these changes
컨플릭트만 해결해서 머지 부탁드려요~~

2023-02-10 10:06 UTC, merged